node {
    echo "${JOB_NAME}"
    echo "${JENKINS_HOME}"
    def repositoryName = JOB_NAME.split("_")[1]

    def tasksGit = [:]
    def tasksGradle = [:]
    def tasksCopy = [:]
    def repositoryGit = new Repository(name: repositoryName, url: "https://github.com/RuslanDN/${repositoryName}.git")

   	tasksGit["${repositoryGit.name}"] = {
   				dir("${repositoryGit.name}") {
   					def gitbr = git branch: 'master', url: "${repositoryGit.url}"
   					print gitbr
   				}
            }
    tasksGradle["${repositoryGit.name}"] = {
				dir("${repositoryGit.name}") {
					sh "./gradlew clean build -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx128m"
				}
			}
	tasksCopy["${repositoryGit.name}"] = {
	                def src = new File("build/libs/${repositoryGit.name}-1.0.0.jar")
                        def dst = new File("${JENKINS_HOME}/cardsBuild/${repositoryGit.name}/${repositoryGit.name}-1.0.0.jar")
                        dst << src.bytes

            }


   	stage("fetching sources") {
         parallel tasksGit
     }

    stage("building sources") {
        parallel tasksGradle
    }

    stage("copy jars") {
        parallel tasksCopy
    }
}

class Repository implements Serializable {
    String url
    String name
}